# Generated by Django 4.1 on 2022-08-17 12:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("customer", "0001_initial"),
        ("showroom", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customercar",
            name="showroom",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="showroom.showroomprofile",
            ),
        ),
    ]
