# Generated by Django 4.1 on 2022-08-08 12:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customer", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customercar",
            name="count",
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name="customercar",
            name="price",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                max_digits=8,
                validators=[django.core.validators.MinValueValidator(0.0)],
            ),
        ),
        migrations.AlterField(
            model_name="customerprofile",
            name="balance",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=8,
                validators=[django.core.validators.MinValueValidator(0.0)],
            ),
        ),
        migrations.AlterField(
            model_name="customerprofile",
            name="email",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
