# Generated by Django 4.0 on 2022-08-25 12:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('showroom', '0001_initial'),
        ('car', '0001_initial'),
        ('dealer', '0001_initial'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactionselltoshowroom',
            name='showroom',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='showroom.showroomprofile'),
        ),
        migrations.AddField(
            model_name='dealerprofile',
            name='cars',
            field=models.ManyToManyField(through='dealer.DealerCar', to='car.Car'),
        ),
        migrations.AddField(
            model_name='dealerprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.user'),
        ),
        migrations.AddField(
            model_name='dealercar',
            name='car',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='car.car'),
        ),
        migrations.AddField(
            model_name='dealercar',
            name='dealer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dealer.dealerprofile'),
        ),
        migrations.AlterUniqueTogether(
            name='dealercar',
            unique_together={('car', 'dealer')},
        ),
    ]
