# Generated by Django 4.1 on 2022-08-17 12:26

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("car", "0001_initial"),
        ("dealer", "0002_initial"),
        ("showroom", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ShowroomSales",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField()),
                (
                    "discount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.01,
                        max_digits=3,
                        validators=[django.core.validators.MinValueValidator(0.0)],
                    ),
                ),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                ("is_active", models.BooleanField()),
                (
                    "car",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="car.car"
                    ),
                ),
                (
                    "showroom",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="showroom.showroomprofile",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DealerSales",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField()),
                (
                    "discount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.01,
                        max_digits=3,
                        validators=[django.core.validators.MinValueValidator(0.0)],
                    ),
                ),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                ("is_active", models.BooleanField()),
                (
                    "car",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="car.car"
                    ),
                ),
                (
                    "dealer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="dealer.dealerprofile",
                    ),
                ),
            ],
        ),
    ]
